import {
  X,
  LucideProps,
  MoreHorizontal,
  User,
  Settings,
  LifeBuoy,
  LogOut,
  Sun,
  Moon,
  LayoutDashboard,
  Command,
  ChevronRight,
  ChevronLeft,
  Calendar,
  HeartPulse,
  GraduationCap,
  Receipt,
  ChevronDown,
  ChevronUp,
  Circle,
  LayoutPanelTop,
  BarChart,
  Kanban,
  Pencil,
  FileText,
  PieChart,
} from "lucide-react";

export const Icons = {
  close: X,
  user: User,
  dotsVertical: MoreHorizontal,
  settings: Settings,
  support: LifeBuoy,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  grid: LayoutPanelTop,
  logo: Command,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  calendar: Calendar,
  pulse: HeartPulse,
  graducationCap: GraduationCap,
  receipt: Receipt,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  circle: Circle,
  layout: LayoutDashboard,
  barChart: BarChart,
  menuLine: Kanban,
  pencil: Pencil,
  file: FileText,
  pieChart: PieChart,
};
